### ISSUE TITLE
Code but no tests?

### ISSUE THREAD

**Issue by pajatopmr** [justland/just-func#1]
I do not see any tests but I do see code for PHP. I would like to review code and point out what I think is clean and what is not so clean if only to better understand what clean code actually is through a discussion with other clean coders. But when there is no tests and very long functions right out of the chute, I think maybe clean code is not a goal. Would that be correct?

**Comment by unional** [comment]
Thanks!
This `just-func` repository contains the specification of the language, so not much implementation going on here.
The tests are basically for JSON schema, which are under the `spec` folder.

The PHP code is a utility code for copying schema, to repository, so for now no tests for it yet (as doing dependency inversion in this code is too complicated for the benefit). :)

You may want to check out [just-func-php](https://github.com/justland/just-func-php), where it contains the implementation and fully tested. :)

Thanks for the issue again!

**Comment by pajatopmr** [comment]
OK, then. The php directory with code threw me off, although it is a bit "off" to have some code but no associated tests. Just saying. :-)
